[package]
edition.workspace = true
name = "cli"
version = "0.1.1"
authors.workspace = true
license.workspace = true
description.workspace = true
[dependencies]
tokio.workspace = true
libunits_converter.workspace = true
clap.workspace = true

[[bin]]
name = "runit_conversion"
path = "./src/main.rs"
